services:
  beaversite:
    image: denoland/deno:latest
    container_name: beaversite
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
    ports:
      - 8080:8080
    volumes:
      - './web:/web'
    command: deno run -A --watch /web/server.ts
    restart: unless-stopped